jobs:
  - name: docker-ecr-ap-r-image-pr
    plan:
      - get: docker-ecr-ap-r-image-pr
        trigger: true
        version: every
      - put: docker-ecr-ap-r-image-pr
        params:
          path: docker-ecr-ap-r-image-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          docker-ecr-ap-r-image: docker-ecr-ap-r-image-pr
      - .: (( inject meta.plan.get-gha-ecr-creds ))
        input_mapping:
          docker-ecr-ap-r-image: docker-ecr-ap-r-image-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          docker-ecr-ap-r-image: docker-ecr-ap-r-image-pr
        params:
          TF_WORKSPACE: "management"
          DETAILED_EXITCODE: ""
        on_failure:
          put: docker-ecr-ap-r-image-pr
          params:
            path: docker-ecr-ap-r-image-pr
            status: failure
        on_success:
          put: docker-ecr-ap-r-image-pr
          params:
            path: docker-ecr-ap-r-image-pr
            status: success
